resource "aws_launch_template" "launch_template" {
  name_prefix                 = var.launch_template_name

  block_device_mappings {
    device_name = var.device_name

    ebs {
      volume_size           = var.volume_size
      volume_type           = var.volume_type
      delete_on_termination = var.is_delete_on_termination
      encrypted             = var.is_volume_encrypted
    }
  }
  image_id                    = data.aws_ami.amazon_linux.id
  instance_type               = var.instance_type
  vpc_security_group_ids      = [aws_security_group.ec2_security_group.id]
  network_interfaces {
    associate_public_ip_address = var.associate_public_ip_address      
  }
  key_name                    = aws_key_pair.aws_autogenerated_key_pair.key_name
  user_data                   = data.template_file.webserver_launch_configuration_user_data.rendered

}

resource "aws_autoscaling_group" "autoscaling_group" {
  name                    = var.autoscaling_group_name
  max_size                = var.max_instance_size
  min_size                = var.min_instance_size
  vpc_zone_identifier     = tolist(aws_subnet.public_subnets.*.id) 
  launch_template {
    id      = aws_launch_template.launch_template.id
    version = aws_launch_template.launch_template.latest_version
  }
  health_check_type       = var.health_check_type
  target_group_arns       = [aws_lb_target_group.target_group.arn]
  default_instance_warmup = 30

}

resource "aws_autoscaling_attachment" "asg_attachment_bar" {
  autoscaling_group_name = aws_autoscaling_group.autoscaling_group.id
  lb_target_group_arn    = aws_lb_target_group.target_group.arn
}

resource "aws_autoscaling_policy" "increase_policy" {
  name                   = "Increase_Policy"
  scaling_adjustment     = 1
  adjustment_type        = "ChangeInCapacity"
  cooldown               = 60
  autoscaling_group_name = aws_autoscaling_group.autoscaling_group.name
}

resource "aws_autoscaling_policy" "decrease_policy" {
  name                   = "Decrease_Policy"
  scaling_adjustment     = -1
  adjustment_type        = "ChangeInCapacity"
  cooldown               = 60
  autoscaling_group_name = aws_autoscaling_group.autoscaling_group.name
}