resource "tls_private_key" "autogenerated_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "aws_autogenerated_key_pair" {
  key_name   = var.aws_key_pair_name
  public_key = tls_private_key.autogenerated_key.public_key_openssh
}

resource "local_file" "local_key_pair" {
  filename        = "${path.module}/ec2_key_pair/${var.aws_key_pair_name}.pem"
  file_permission = "0400"
  content         = tls_private_key.autogenerated_key.private_key_pem
}